[tool.poetry]
name = "admin-panel"
version = "0.1.0"
description = "Django admin panel"
authors = ["Dan"]

package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
